#!/usr/bin/with-contenv sh

# wait until influxdb service is 'up'
s6-svwait -u -t 10000 /var/run/s6/services/influxdb

# wait until influxdb is ready
influxdb-ready

# wait until authentication has been setup
influxdb-protected

exec s6-setuidgid influxdb telegraf -config /etc/telegraf/telegraf.toml &>$TELEGRAF_LOG_FILE;
