#!/usr/bin/with-contenv sh

#
# This script will wait until another Consul server is available before starting Consul.
#

# Bind to the external (LAN) IP.
BIND=`host-ip`

# Wait until another Consul server is available.
consul-available

# We have another Consul server available. Join it.
RETRY_JOIN=`consul-join`

# Provide an entry point for Consul WAN customisation.
CONSUL_JOIN_WAN=`consul-join-wan`

# Retrieve a UUID for -node-id.
NODE_ID=`consul-node-id`

# Start Consul.
s6-setuidgid $CONSUL_RUNAS consul agent -node-id $NODE_ID -data-dir $CONSUL_DATA_DIR -config-dir $CONSUL_CONFIG_DIR -bind $BIND -advertise $BIND -client $CONSUL_CLIENT $RETRY_JOIN -retry-interval $CONSUL_RETRY_INTERVAL -domain $CONSUL_DOMAIN -datacenter $CONSUL_DC $CONSUL_JOIN_WAN
