#!/usr/bin/env bash

# check if rabbitmq.config file is set
if [ -f /etc/rabbitmq/rabbitmq.config ]; then
	echo ">>> Rabbitmq will use custom settings from the config file."
  exit 0
fi

# check if RABBITMQ_USER_SET is defined
if [ -f /.rabbitmq-user-set ]; then
	echo ">>> RabbitMQ user account already set!"
  exit 0
fi

# create file so that it can be used to skip the code below next time the rabbitmq server restarts
touch /.rabbitmq-user-set

mkdir -p /etc/rabbitmq

if [ -z "$RABBITMQ_USER" -o -z "$RABBITMQ_PASS" ]; then
	echo ">>> Environment variables RABBITMQ_USER and RABBITMQ_PASS is not defined!"
	echo ">>> RabbitMQ will use default user settings."
	echo "[{rabbit, [{loopback_users, []}]}]." > /etc/rabbitmq/rabbitmq.config
	exit 0
fi

echo "[{rabbit, [{default_user, <<\"$RABBITMQ_USER\">>},{default_pass, <<\"$RABBITMQ_PASS\">>},{tcp_listeners, [{\"0.0.0.0\", 5672}]}]}]." > /etc/rabbitmq/rabbitmq.config
echo ">>> RabbitMQ will use customised user settings."
