#!/usr/bin/with-contenv sh

# If /etc/rabbitmq/rabbitmq.config is already set, we should stop here.
if [ -f /etc/rabbitmq/rabbitmq.config ]; then
	echo ">>> RabbitMQ will use the provided config file."
  exit 0
fi

# If the env variables RABBITMQ_USER and RABBITMQ_PASS have been defined,
# use them to customise our setup.
if [ -n "$RABBITMQ_USER" -a -n "$RABBITMQ_PASS" ]; then
	echo ">>> Setting RabbitMQ username and password."
	cat /etc/rabbitmq/rabbitmq.config.basic > /etc/rabbitmq/rabbitmq.config
	sed -i "s,GUEST_USER,$RABBITMQ_USER,g" /etc/rabbitmq/rabbitmq.config
	sed -i "s,GUEST_PASS,$RABBITMQ_PASS,g" /etc/rabbitmq/rabbitmq.config
	exit 0
fi

# Last option is to simply move across the most basic configuration.
mv /etc/rabbitmq/rabbitmq.config.default /etc/rabbitmq/rabbitmq.config
