#!/usr/bin/with-contenv sh

chown -R consul:consul /var/run/s6/services/consul-template

# Bind to the external (LAN) IP
JOIN=`getent hosts consul-agent | awk '{print $1}'`

exec s6-setuidgid consul consul agent -config-dir /etc/consul/conf.d -retry-join ${JOIN} -retry-interval 15s;
