#!/usr/bin/with-contenv sh

# Bind to the external (LAN) IP
JOIN=`getent hosts consul-agent | awk '{print $1}'`

# Bind to the external (LAN) IP.
BIND=`getent hosts $HOSTNAME | awk '{print $1}'`

# Start Consul in agent mode (see /etc/consul/conf.d/bootstrap/_base.json).
s6-setuidgid consul consul agent -config-dir /etc/consul/conf.d -bind $BIND -client $BIND -retry-join $JOIN -retry-interval 15s -domain $CONSUL_DOMAIN
