#!/usr/bin/with-contenv sh

#
# This script will wait until another Consul server is available before starting Consul.
#

# Bind to the external (LAN) IP.
BIND=`container-ip`

# Wait until another Consul server is available.
consul-available

# We have another Consul server available. Join it.
JOIN=`consul-join`

# Start Consul in Server mode (see /etc/consul/conf.d/bootstrap/config.json).
s6-setuidgid consul consul agent -config-dir /etc/consul.d -client $BIND $JOIN -retry-interval 5s -ui
