#!/usr/bin/with-contenv sh

# wait 5s for `consul agent` to become available
s6-svwait -u -t 5000 /var/run/s6/services/consul

# wait 5s before running consul-template, this should be enough for consul agent to connect to consul server
tries=0
until [ $tries -ge 5 ]; do
  consul_node=`consul members | grep -c "Node"`
  
  if [ $consul_node -gt 0 ]; then
    break;
  fi
  
  sleep 1
  n=$[$n+1]
done

exec consul-template -config /etc/consul-template/conf.d/;
