#!/usr/bin/env sh

# This is a simple and portable (POSIX) shell script

VERSION=""
TAG="alpine-nginx-nodejs"
TRIGGER_URL="https://registry.hub.docker.com/u/smebberson/alpine-nginx-nodejs/trigger/426798eb-bef7-4926-b9f4-cea15301171b/"

# output information about how to use this script
usage()
{
    echo ""
    echo "Use this to create a remote build on Docker Hub."
    echo ""
    echo "./tag -v [version] -c [\"Comment\"]"
    echo ""
    echo "\t-h --help"
    echo "\t-v [version] The new version (without v) to append to 'alpine-nginx-nodejs-v' to create the complete tag name 'alpine-nginx-nodejs-v1.0.0' that resides within Git.".
    echo ""
    echo ""
}

if [ "$1" = "--help" ]; then
    usage
    exit
fi

while getopts "hv:c:" OPTION
do
    case $OPTION in
        h)
            usage
            exit
            ;;

        v)
            VERSION=$OPTARG
            ;;

        ?)
            usage
            exit 1
            ;;
    esac
done

TAG="$TAG-v$VERSION"

if test "$VERSION" != ""; then
    curl -vH "Content-Type: application/json" --data '{"source_type": "Tag", "source_name": "$TAG"}' -X POST $TRIGGER_URL
    echo "\n"
    exit
fi

# if the version wasnt set, output the help
usage
exit 1;
